### ISSUE TITLE
Browserify gulp fails

### ISSUE THREAD

**Issue by likeadeckofcards** [lishengzxc/vue-sweetalert#5]
I am trying to perform gulp on a file that contains vue-sweetalert and I keep getting the following errors:

```
{ Error: Cannot find module 'Vue' from '/home/forge/farfield.local/node_modules/vue-sweetalert/build'
    at /home/forge/farfield.local/node_modules/resolve/lib/async.js:46:17
    at process (/home/forge/farfield.local/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/forge/farfield.local/node_modules/resolve/lib/async.js:188:17)
    at load (/home/forge/farfield.local/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/forge/farfield.local/node_modules/resolve/lib/async.js:92:31)
    at /home/forge/farfield.local/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
[12:06:34] Finished 'browserify' after 5.33 s
[12:06:34] Starting 'browserify'...
{ Error: Cannot find module 'Vue' from '/home/forge/farfield.local/node_modules/vue-sweetalert/build'
    at /home/forge/farfield.local/node_modules/resolve/lib/async.js:46:17
    at process (/home/forge/farfield.local/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/forge/farfield.local/node_modules/resolve/lib/async.js:188:17)
    at load (/home/forge/farfield.local/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/forge/farfield.local/node_modules/resolve/lib/async.js:92:31)
    at /home/forge/farfield.local/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream:
   Labeled {
     _readableState:
      ReadableState {
        objectMode: true,
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events:
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState:
      WritableState {
        objectMode: true,
        highWaterMark: 16,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object] ],
     length: 1,
     label: 'deps' } }
```

Even reverting to the previous version does not help.

**Comment by lishengzxc** [comment]
[#6](https://github.com/lishengzxc/vue-sweetalert/pull/6)  You can try to upgrade it

**Comment by likeadeckofcards** [comment]
Thank you that fixed it.
